#DATA LOADING AND DATA STORAGE
DATA SOURCE -> DATA LOAD -> PANDAS DATAFRAME-> DATA INSPECTION -> DATA STORAGE

In [73]:
print("Importing panads")
import pandas as pd

Importing panads

In [74]:
import os
print("Current working directory:")
#os.getcwd() returns the current working directory as a string
print(os.getcwd())

Current working directory:
/content

In [75]:
print("Files and folders:")
#os.listdir() lists the files and folders in the given directory ('.',)
print(os.listdir())

Files and folders:
['.config', 'student.pkl', 'df.pkl', 'students.csv', 'students.text', 'AB_index.txt', 'AB_index.xlsx', 'output.txt', 'student_pqt.parquet', 'students.txt', 'AB.csv', '.ipynb_checkpoints', 'AB_index.json', 'sample_data']

In [76]:
pd.DataFrame({
    "A": [1,2,3],
    "B":[4,5,6]
}).to_csv("AB.csv",index=False)
A_B=pd.read_csv("AB.csv")
A_B

   A  B
0  1  4
1  2  5
2  3  6

In [77]:
A_B.to_csv("AB_index.txt",sep="|",index=False)
A_B_index = pd.read_csv("AB_index.txt")
A_B_index

   A|B
0  1|4
1  2|5
2  3|6

In [78]:
A_B.to_excel("AB_index.xlsx",index=False)
A_B_index = pd.read_excel("AB_index.xlsx")
A_B_index

   A  B
0  1  4
1  2  5
2  3  6

In [79]:
A_B.to_json("AB_index.json",orient="records")
A_B_index = pd.read_json("AB_index.json")
A_B_index

   A  B
0  1  4
1  2  5
2  3  6

In [80]:
A_B.head()

   A  B
0  1  4
1  2  5
2  3  6

In [81]:
A_B.tail()

   A  B
0  1  4
1  2  5
2  3  6

In [82]:
with open("output.txt", "w") as f:
  print(A_B, file=f)

In [83]:
print("Shape")
print(A_B.shape)

Shape
(3, 2)

In [84]:
print("Data Types")
print(A_B.dtypes)

Data Types
A    int64
B    int64
dtype: object

In [85]:
print("Columns")
print(A_B.columns)

print("Size")
print(A_B.size)

print ("Values")
print(A_B.values)

print("Index")
print(A_B.index)

Columns
Index(['A', 'B'], dtype='object')
Size
6
Values
[[1 4]
 [2 5]
 [3 6]]
Index
RangeIndex(start=0, stop=3, step=1)

In [86]:
#sep: specify the separator
#header:identify the header roww
#names:provie column names
#index_col:use a column as the index
#use cols:load selected columns
#uecols:load a limited number of rows
#skiprows:skip rows

In [87]:
#TXT.TXT.FILE
#CREATE TEXT FILE , DATA ENTER | WRITE OPERATION
with open("students.txt","w") as file:
  file.write("Name,Department,Marks,City\n"),
  file.write("Astik,CSE,85,AGRA \n")
  file.write("Abhiyank,IT,88, MATHURA \n")
  file.write("Aditya,CSE,98,NOIDA \n")
  file.write("Ayansh,IT,80,ALIGARH \n")
#CONVERSION OF TXT FILE INTO CSV FILE

In [88]:
with open("students.txt","r") as file:
  data=file.read()
print(data)

Name,Department,Marks,City
Astik,CSE,85,AGRA
Abhiyank,IT,88, MATHURA
Aditya,CSE,98,NOIDA
Ayansh,IT,80,ALIGARH

#SAVE THE .txt DATA into .CSV file

In [89]:
import pandas as pd
student_df=pd.read_csv("students.txt")
student_df.to_csv("students.csv",index=False)
student_df

       Name Department  Marks       City
0     Astik        CSE     85      AGRA
1  Abhiyank         IT     88   MATHURA
2    Aditya        CSE     98     NOIDA
3    Ayansh         IT     80   ALIGARH

In [90]:
#JSON FILE

In [91]:
#EXCEL

In [92]:
#PICKLE
df=pd.DataFrame({
    "Name":["Astik","Abhiyank","Aditya","Ayansh"],
    "Marks":[85,88,98,80]
})
df.to_pickle("student.pkl")
df_pickle=pd.read_pickle("student.pkl")
df_pickle

       Name  Marks
0     Astik     85
1  Abhiyank     88
2    Aditya     98
3    Ayansh     80

In [93]:
#save the Dataframe into pickle
df.to_pickle("student.pkl")
df_pickle

       Name  Marks
0     Astik     85
1  Abhiyank     88
2    Aditya     98
3    Ayansh     80

In [94]:
student_pkl=pd.read_pickle("student.pkl")
student_pkl

       Name  Marks
0     Astik     85
1  Abhiyank     88
2    Aditya     98
3    Ayansh     80

#
WEB SCRAPPING

In [95]:
import requests
from bs4 import BeautifulSoup
url="https://www.amazon.in/"
page=requests.get(url)
soup=BeautifulSoup(page.text,"html.parser")

In [96]:
print(soup.title.text)

Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in

#PARQUET

In [97]:
df_parquet=df_pickle

In [98]:
print(df_parquet)

       Name  Marks
0     Astik     85
1  Abhiyank     88
2    Aditya     98
3    Ayansh     80

In [99]:
df_parquet.to_parquet("student_pqt.parquet",index=False)

In [100]:
#read the parquet file
df_parquet_file=pd.read_parquet("student_pqt.parquet")
df_parquet

       Name  Marks
0     Astik     85
1  Abhiyank     88
2    Aditya     98
3    Ayansh     80

#SQLITE

In [101]:
import sqlite3
conn=sqlite3.connect("students.db")

In [102]:
cursor=conn.cursor()
print("Database Created Successfully")

Database Created Successfully

In [103]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS student_table(
NAME TEXT,
ROLL_NO INTEGER,
MARKS INTEGER)

""")

print("Table is created Successfully !!")

Table is created Successfully !!

In [104]:
#write the data into table
cursor.execute("INSERT INTO student_table VALUES('Astik',1,85)")
cursor.execute("INSERT INTO student_table VALUES('Abhiyank',2,88)")
cursor.execute("INSERT INTO student_table VALUES('Aditya',3,98)")
cursor.execute("INSERT INTO student_table VALUES('Ayansh',4,80)")
cursor.execute("INSERT INTO student_table VALUES('Ayush',5,80)")

In [105]:
conn.commit()
print('Recordes inserted successfully !!')
conn.close()

Recordes inserted successfully !!

In [106]:
#Retrive | read the data
conn=sqlite3.connect("students.db")
cursor=conn.cursor()
cursor.execute("SELECT * FROM student_table")
rows=cursor.fetchall()
for row in rows:
  print(row)
  conn.close()

('Astik', 1, 85)
('Abhiyank', 2, 88)
('Aditya', 3, 98)
('Ayansh', 4, 80)
('Ayush', 5, 80)